apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
#          image: random-order-payments:local
          image: ${PAYMENTS_IMAGE}
#          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: SPRING_DATA_MONGODB_URI
#              value: "mongodb://root:rootpassword@mongodb:27017/payments?authSource=admin"
              value: "mongodb+srv://root:rootpassword@cluster0.oie64di.mongodb.net/payments?appName=Cluster0"
---
apiVersion: v1
kind: Service
metadata:
  name: payments
spec:
  selector:
    app: payments
  ports:
    - port: 8081
      targetPort: 8081
